formatter: "markdown table"
output:
  file: "README.md"
sections:
  show:
    - requirements
    - providers
    - resources
    - inputs
settings:
  anchor: true
  color: true
  hide-empty: true
  lockfile: true