name: Generate diagram
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  tfmermaid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: asannou/tfmermaid-action@v1
        with:
          file: DIAGRAM.md
      - name: commit
        run: |
          git add DIAGRAM.md
          if ! git diff --cached --quiet --exit-code
          then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "generated"
            git push
          fi
